### ISSUE TITLE
How to install.

### ISSUE THREAD

**Issue by JakGfx** [Mcfloy/launchpad#3]
A better how to install would be great, i had to download thousand of things and nothing worked, probably an issue on my part but a better explanation would be great, i find the installation hard and i do not know what do i need to do in order to start the program, i have a launchpad x. Some help would be really appreciated.
Discord name: JakGfx

**Comment by JakGfx** [comment]
![Cx8nEP09S4](https://github.com/Mcfloy/launchpad/assets/89050861/02125a19-1c27-487e-914a-56fd14e574c0)
Managed to install it but when i try to start it by clicking on the exe it doesn't want to open

**Comment by Mcfloy** [comment]
Can you check if in the config.yaml you have `bookmark_1: pages` configured so that it load the folder first?

**Comment by JakGfx** [comment]
![bUmaR9rcI9Jq](https://github.com/Mcfloy/launchpad/assets/89050861/b0d8c288-a469-4220-a563-f6d9d5216014)
Still don't understand how to set up pages, im not a coder so that's why i asked for more clear instruction, i get this error and i don't know what to do. Thanks.

**Comment by Mcfloy** [comment]
> Still don't understand how to set up pages, im not a coder so that's why i asked for more clear instruction, i get this error and i don't know what to do. Thanks.

Yep my bad on this I'll try to implement more user-friendly solutions for this project. Meanwhile for your `pages.csv` you can remove the first line, it should look like this:

```
11;pew.mp3;13
```

Note that 11 is the coordinate for the bottom left note, going from 11 to 18 for the first row, 21 to 28 for the second row, etc. the x9th note is for the bookmark notes so it should not be used.

**Comment by JakGfx** [comment]
Ok now it works, excellent! How do i add more pages to my launchpad? 
`11;pew.mp3;13` <= Also 11 is the number of the key that im going to press but what does the last number do? Thanks.

**Comment by Mcfloy** [comment]
> How do i add more pages to my launchpad?

Just add a new file and the launchpad will add the top buttons for the pagination, you'll need to execute again the launchpad (no need to recompile at this point, your .exe is sufficient)

The `13` is the color of the note, there's an [image](https://github.com/Mcfloy/launchpad/blob/main/colors.png) of the colors possibility handled on the README.md, in this case it should appear as a yellow note.

Also the bookmark is another level of categorizing your folders (each folder containing a list of files that each represent a page of notes) that will appear at the right of the launchpad.

**Comment by JakGfx** [comment]
Program works like a charm now, i will consider doing a tutorial when i have some time to spare, very nice program to recycle an unused launchpad!
